### ISSUE TITLE
Add support for command line arguments

### ISSUE THREAD

**Issue by metrafonic** [kzvi/vsc-pandoc-markdown-preview#1]
Thank you for your excellent extension!

Is it possible to add an option to define extra command line arguments.

For example, i use `pandoc --filter pandoc-citeproc` to enable citations in markdown.

Regards,
metrafonic

**Comment by kzvi** [comment]
I added this feature, it should be published now. Enjoy!

**Comment by metrafonic** [comment]
Wow thank you!
It seems to work well.

Is it possible to run the command pandoc command with the current working directory being the same as the markdown file location. This way, things defined in the markdown yaml can be relative, not absolute. For example:
```markdown
---
abstract: fgsfdgsdfgsdf
author: asdfasd
bibliography:
- 'bibliography.bib'
title: 'Example'
---
Example file
```
instead of the currently needed:
```markdown
---
abstract: fgsfdgsdfgsdf
author: asdfasd
bibliography:
- '/home/user/patth/to/bibliography.bib'
title: 'Example'
---
Example file
```

thank you for your extention!

**Comment by kzvi** [comment]
Good catch. I fixed it.
