### ISSUE TITLE
Request: Scroll lock with source text

### ISSUE THREAD

**Issue by matthewbegun** [kzvi/vsc-pandoc-markdown-preview#2]
Hi, thanks for making this, I have been meaning to write one but I don't know js/ts and haven't had the will to get started yet.

It would be awesome if it could sync the preview and source windows the way the default previewer can. I'm not sure how hard that is to do.

Thanks again for making this extension!

**Comment by kzvi** [comment]
Unfortunately I think that this would be prohibitively difficult. Any solution that doesn't involve modifying pandoc would probably be hacky and fragile.

**Comment by mitinarseny** [comment]
> Unfortunately I think that this would be prohibitively difficult. Any solution that doesn't involve modifying pandoc would probably be hacky and fragile.

It is already implemented in [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/) though

**Comment by matthewbegun** [comment]
Closing this as I'm giving the other one a try. Thanks!
