### ISSUE TITLE
YAML Abstract not visible

### ISSUE THREAD

**Issue by alfureu** [kzvi/vsc-pandoc-markdown-preview#6]
The preview addon does not display the abstract in any of the standard formats specified in the YAML front matter, e.g.:

```
---
abstract: |
   Abstract paragraph 1.
   Abstract paragraph 2.
---
```
nor ..,

```
---
abstract : "Abstract text."
---
```

Could you please fix/implement this? I would suggest to specify the abstract font 2em smaller than the pre-defined normal text (maybe with justified paragraph?) font size, to make it visibly distinguishable from the rest in the preview window. An option for justifying the whole document would be great too.

**Comment by kzvi** [comment]
This would have to be a feature implemented in pandoc itself. Try posting an issue there.

**Comment by alfureu** [comment]
It is implemented in pandoc, hence the request. If you convert the .md file into docx or pdf, the abstract is rendered. It is this vscode plugin which does not render abstract in the text.
